### ISSUE TITLE
Remove `usize` from types in conda_package_types

### ISSUE THREAD

**Issue by wolfv** [mamba-org/rattler#102]
I think `usize` is platform dependent and will be an `u32` on 32 bit systems and a `u64` on 64 bit systems. 

I think that doesn't make much sense for structs that are parsed or written to from JSON since it'd be better to strictly encode the maximum size for these integers regardless of the host CPU architecture.

WDYT @baszalmstra ?

**Comment by baszalmstra** [comment]
Yeah I agree, good catch!

**Comment by wolfv** [comment]
I did a bunch of them in https://github.com/mamba-org/rattler/pull/101 but there are more :)

**Comment by wolfv** [comment]
Done in #105
