### ISSUE TITLE
Typed checksums

### ISSUE THREAD

**Issue by wolfv** [mamba-org/rattler#134]
Currently we're storing SHA256 and MD5 hashes as strings. I am wondering if it would be better to store them as typed byte arrays and de-/serialize them at the serde level only?

**Comment by baszalmstra** [comment]
I like that a lot in different places in the codebase we now convert back and forth. `rattler_digest` should also already provide most of the things needed.

**Comment by wolfv** [comment]
And it would be nice if we don't need to have sha2 and md5 crates outside of rattler digest (rather reexport them)
