### ISSUE TITLE
PathsJson, make sure that we serialize in alphabetical order

### ISSUE THREAD

**Issue by wolfv** [mamba-org/rattler#141]
To improve the reproducibility of packages, we should serialize the `paths` in alphabetical order. This means we need to sort the `Vec<PathsEntry>` before serializing alphabetically on the `_path` attribute. 

Similarly the `has_prefix`, `files` text files should always be sorted deterministically (alphabetically).

**Comment by nachiketkanore** [comment]
This issue has been solved recently. Kindly close it to avoid confusion!

**Comment by wolfv** [comment]
Thanks for the reminder @nachiketkanore :)
