### ISSUE TITLE
Use default_cache_dir in create

### ISSUE THREAD

**Issue by wolfv** [mamba-org/rattler#142]
Currently a rattler user has to choose the cache dir but I think it would be convenient if we export the default value uses (`dirs::cache_dir().join("rattler/cache")`).

**Comment by baszalmstra** [comment]
There is already https://docs.rs/rattler/0.2.0/rattler/fn.default_cache_dir.html

Does that do what you need?

**Comment by wolfv** [comment]
yeah! I think we're not using it in `create.rs`?

**Comment by wolfv** [comment]
https://github.com/mamba-org/rattler/blob/c4815c35da3b54b9ec74c6a56eab4af6e548499f/crates/rattler-bin/src/commands/create.rs#L54-L58

**Comment by baszalmstra** [comment]
Jep! Lets replace it there!
