### ISSUE TITLE
Write package - include size hint for zstd?

### ISSUE THREAD

**Issue by wolfv** [mamba-org/rattler#195]
Apparently it's possible to give zstd a hint for the "decompressed size" of the tarball and that is supposed to improve memory usage when decoding.

The conda team added this as described here: https://conda.discourse.group/t/conda-package-streaming-0-8-0-and-conda-package-handling-2-1-0-released/267

**Comment by baszalmstra** [comment]
Do you know if there is an API available in rust that we can use?

**Comment by wolfv** [comment]
We already did this :)

**Comment by wolfv** [comment]
In #469
