### ISSUE TITLE
Implement shell detection

### ISSUE THREAD

**Issue by baszalmstra** [mamba-org/rattler#216]
We use very dumb logic [to detect the _current_ shell.](https://github.com/mamba-org/rattler/blob/a6979586f7ba9e92a510da5c160d4530ec02252f/crates/rattler_shell/src/shell/mod.rs#L298) I would like to have a proper implementation. We can base it on: https://docs.rs/clap_complete/latest/clap_complete/shells/enum.Shell.html#method.from_env

Ideally, we also have a function to return the "_default_" shell for the platform. This can then be used when spawning a shell when the current one cannot be used.

**Comment by wolfv** [comment]
In micromamba, we look at the parent process name and try to infer the running shell from that.
