### ISSUE TITLE
`~=2.4,<4` is evaluated wrongly

### ISSUE THREAD

**Issue by wolfv** [mamba-org/rattler#225]
The MatchSpec currently also matches `3.1` or other versions. In fact, the `<4` should be completely ignored, and the matchspec should match only `2.4.*`.

**Comment by wolfv** [comment]
I already have a fix, but still confused about the proper behavior of `~=`...

**Comment by wolfv** [comment]
I used this:

```rust
            VersionSpec::Operator(VersionOperator::Compatible, limit) => version >= limit && version < &limit.bump(),
            VersionSpec::Operator(VersionOperator::NotCompatible, limit) => version < limit || version > &limit.bump(),
```

**Comment by wolfv** [comment]
Hmm, so the conda implementation is

```py
def compatible_release_operator(x, y):
    return op.__ge__(x, y) and x.startswith(
        VersionOrder(".".join(str(y).split(".")[:-1]))
    )
```

... 

So I think for `~=2.2` it should match `>=2.2,2.*`

**Comment by baszalmstra** [comment]
I fixed this in:

- https://github.com/mamba-org/rattler/pull/227

It was a bit of a coincidence that this issue popped up but I was working on refactoring the Version anyway.
