### ISSUE TITLE
No dependency hell for contributors

### ISSUE THREAD

**Issue by YeungOnion** [mamba-org/rattler#282]
It would be nice to have a way to make contributing easy and portable. I'll work on this and add a mention to it in the Contributing section of the README.

**Comment by YeungOnion** [comment]
I thought of a Dockerfile; if I understood them, Ruben mentioned (in discord chat) making it a pixi project. I don't actually know if the pixi solution would remove the need for docker.

If not, it seems excessive to have an image that has a venv (made and managed by pixi), then run the build within that venv, does it not?

**Comment by YeungOnion** [comment]
Would like to rename the issue to "No dependency hell for contributors"

**Comment by YeungOnion** [comment]
Yeah, I'll work on it! 🤠

**Comment by wolfv** [comment]
love the title :D

**Comment by YeungOnion** [comment]
fixed in #283
