### ISSUE TITLE
Implement strict priority for channels

### ISSUE THREAD

**Issue by wolfv** [mamba-org/rattler#297]
We don't prioritize channels yet. We should have a flag in the solver that toggles strict priority.

Strict priority means that if a package name is available in a higher priority repository it is ignored in lower-priority repositories. 

If there are two repositories, A & B and A is added with higher priority, only `numpy` from package A is going to be considered even if a higher version exists in B.

**Comment by baszalmstra** [comment]
This has been implemented in #385
