### ISSUE TITLE
Test extraction using an expected hash

### ISSUE THREAD

**Issue by baszalmstra** [mamba-org/rattler#40]
Currently, the tests for package extraction just check if the process doesn't error out. This doesn't really test if a package is properly extracted. 

The tests for validating packages do use the same code to extract a package and validate its content but it would be nice if we could compute a sha256 hash of an extracted package and validate that that is indeed what we would expect.

We can use the `rstest` crate to create test cases with the package to extract and an expected hash as an input. e.g.:

```rust
#[rstest]
#[case("some_package.conda", "somecomplexshahashnumber")]
fn validate_extracted_packages(#[case] path: &str, #[case] hash: &str) {
 // ...
}
```

When developing this feature some care is required to ensure that symlinks are properly hashed. I think it would be better to hash the link itself instead of the content it points to. This is because `../a` and `./../a` refer to the same file but are different symlinks.

**Comment by wolfv** [comment]
I think we're now checking all the files in the extracted packages folder when linking, so we can be at least reasonably sure that this is indeed working fine :)

**Comment by baszalmstra** [comment]
This has been added a while back.
