### ISSUE TITLE
Functionality to create and manage `lockfiles`

### ISSUE THREAD

**Issue by Wackyator** [mamba-org/rattler#404]
To make environments reproducible, it would be really great to have some functionality to create and manage the lockfiles from py-rattler itself instead of plugging some external library to do it. 

`rattler_lock` already provides this functionality in rust, it would be great to have some abstraction around it.

**Comment by baszalmstra** [comment]
What is still missing @Wackyator or can we close this?

**Comment by Wackyator** [comment]
Completed with #510 & #541
