### ISSUE TITLE
Extend `version.bump()` to allow bumping `minor|major|patch`

### ISSUE THREAD

**Issue by hadim** [mamba-org/rattler#449]
See https://github.com/prefix-dev/pixi/pull/579#discussion_r1430662134 for context.

API could be one of those:

- `version.bump_{minor|major|patch}()`
- `version.bump(BumpType::{Major|Minor|Patch|Last})`

Any preference?

**Comment by baszalmstra** [comment]
Hey @hadim ! This is not completely trivial. For instance how would you bump: `1a.2b.3c`? When you add this I think you need lots of tests. :)

I have no strong preference for either API!

**Comment by hadim** [comment]
Indeed, it is not! But supporting something like `1.1.1` would probably cover already many cases' no? And maybe we can just raise an error for the remaining?

**Comment by hadim** [comment]
I gave it a first try: https://github.com/mamba-org/rattler/pull/452

**Comment by baszalmstra** [comment]
Closed by #452
