### ISSUE TITLE
Consider removing unused fields (like `content_hash`) from lock files

### ISSUE THREAD

**Issue by baszalmstra** [mamba-org/rattler#465]
I suggest we remove `content_hash` and some other metadata fields from our implementation, since we are able to verify that a lock-file satisfies certain requirements without all this information anyway.

At the moment `rattler_lock` is slowly diverging from conda lock. At this point the two formats are no longer compatible anyway. I expect that in the future we'll diverge further anyway.

See https://github.com/conda/conda-lock/issues/432.

**Comment by wolfv** [comment]
yeah I am fine with this. I think we could try to go through a CEP process for the lockfile at some point, and then maybe conda-lock can align themselves with our format.
