### ISSUE TITLE
Consolidate dependencies in workspace `Cargo.toml`

### ISSUE THREAD

**Issue by vlad-ivanov-name** [mamba-org/rattler#481]
A lot of dependencies, e. g. `tracing`, are used by multiple crates in the project, and the version for each is set separately.

![image](https://github.com/mamba-org/rattler/assets/2057191/db41cb17-83ab-4f41-b4fa-728727ea2143)

This makes it difficult to prevent duplicated packages and update versions.

One way to solve this is to use workspace dependencies as described here:

https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#inheriting-a-dependency-from-a-workspace

Version divergence could be checked with cargo-deny:

https://embarkstudios.github.io/cargo-deny/checks/bans/index.html#use-case---duplicate-version-detection

**Comment by wolfv** [comment]
That would be great!

**Comment by baszalmstra** [comment]
Yeah indeed! Workspace dependencies sounds perfect for this. Would you be able to create a PR?
