### ISSUE TITLE
System certificates are ignored with the rustls version

### ISSUE THREAD

**Issue by pavelzw** [mamba-org/rattler#491]
When using rattler-build with the openssl version (i.e. from conda-forge), it succeeds when you have corporate SSL certificates in your system certificates. When you use the rattler-build version with rustls (i.e. the musl one from the build artifacts), it ignores the system certificates.

**Comment by baszalmstra** [comment]
Should be easily fixed by applying the same trick we did in pixi: https://github.com/prefix-dev/pixi/pull/310

**Comment by baszalmstra** [comment]
Shouldnt this issue be in rattler-build though?

**Comment by pavelzw** [comment]
Yes, I thought this was an option that needed to be specified in rattler.
