### ISSUE TITLE
`rattler_conda_types::Version::to_string()` does not preserve case

### ISSUE THREAD

**Issue by 0xbe7a** [mamba-org/rattler#527]
When uploading packages with rattler-build, we use different fields from parsed IndexJson to upload packages to anaconda.org. If we attempt upload a package with version `1.2.3_Beta1`, it will fail because the original version case is lost after parsing and `version.to_string()` will return `1.2.3_beta1`. Subsequently a release `1.2.3_beta1` is created but anaconda.org rejects the package upload as the versions from the IndexJson and the release are not the same. While it is true that `1.2.3_Beta1` == `1.2.3_beta1` when comparing versions, rattler should return the version with the original version when calling `.to_string()`.

The following unit-test should pass:

```rust
#[test]
fn preserve_case() {
    let v = "1.2.3-Beta1";
    let version = Version::from_str(v).unwrap();
    assert_eq!(version.to_string(), v);
}
  ```

**Comment by baszalmstra** [comment]
We have [VersionWithSource](https://docs.rs/rattler_conda_types/latest/rattler_conda_types/struct.VersionWithSource.html) for that use case. Does that help?

**Comment by 0xbe7a** [comment]
Yeah, missed it. Works perfectly for this use-case
