### ISSUE TITLE
Replace very long shebangs with a shorter variant

### ISSUE THREAD

**Issue by wolfv** [mamba-org/rattler#593]
I noticed that when installing `sip-build` rattler seems to fail to replace a 'very long shebang'.

Shebangs have a limit of 127 characters on most systems. 

Conda/Mamba replace the shebang with something like `!#/usr/bin/env python` (instead of the full path to Python).

**Comment by wolfv** [comment]
https://www.in-ulm.de/~mascheck/various/shebang/#length

https://stackoverflow.com/questions/10813538/shebang-line-limit-in-bash-and-linux-kernel

**Comment by jaimergp** [comment]
See this conda snippet for our workaround there:

https://github.com/conda/conda/blob/514c647c80b999d7490cb3c3efee3e12736d488b/conda/core/portability.py#L299-L325

**Comment by wolfv** [comment]
Actually we've fixed this recently :)
