### ISSUE TITLE
Prefix with spaces does not work for some executables / entry points on Windows

### ISSUE THREAD

**Issue by wolfv** [mamba-org/rattler#607]
With pixi, I created an env on Windows on a path like `C:\bla\test with spaces\env`.

Most things work (e.g. `pixi run python` etc.).

However, some entry points do not work for unknown reason (maybe a problem with the launcher?).

```
.\.pixi\envs\default\Scripts\jupyter-notebook.exe
pixi run jupyter notebook
pixi run jupyter-notebook
```

All fail with "failed to create process." (on PowerShell).

```
pixi run python .\.pixi\envs\default\Scripts\jupyter-notebook-script.py
```

This last one works fine and boots up jupyter notebook.

**Comment by wolfv** [comment]
Just tried "pixi run flask" and it also has the `failed to create process` issue. 

So I think this might be related to `noarch` packages and our bundled launcher`

**Comment by baszalmstra** [comment]
Fixed by https://github.com/mamba-org/rattler/pull/611
