### ISSUE TITLE
force docs on public functions and structs.

### ISSUE THREAD

**Issue by baszalmstra** [mamba-org/rattler#61]
All public methods in rattler crates should have proper docs. We can force this with `#![warn(missing_docs)]` or even `#![deny(missing_docs)]`. Some crates already have this but we need to play catchup for some of the others.

**Comment by baszalmstra** [comment]
Crates that still need to be fixed:

* `rattler` 
* `rattler_conda_types` 
* `rattler_package_streaming` (#64 )
* `rattler_virtual_packages` (#63 )

**Comment by wolfv** [comment]
- rattler_conda_types has been fixed! :)

**Comment by wolfv** [comment]
I think the only two crates left are `rattler` and `rattler_macros`. Both are very much doable.

**Comment by wolfv** [comment]
fixed by #268
