### ISSUE TITLE
Remove uncommented code (or clarify why it's there)

### ISSUE THREAD

**Issue by aochagavia** [mamba-org/rattler#634]
I came across this code snippet while going through the source code: https://github.com/mamba-org/rattler/blob/526cd23b08fd497fb2811af12f3d615dc1229200/crates/rattler_conda_types/src/match_spec/parse.rs#L111-L117

I don't understand the code well enough to know whether the comment needs to be removed, but it looks like an oversight. This issue is to make sure you are aware (and a suggestion to clarify why the commented code needs to be there, if it is actually on purpose).

**Comment by wolfv** [comment]
Well, I think this came from `conda`: https://github.com/conda/conda/blob/ad615752a7efa20f8ba135e2fa31417807dcfefb/conda/models/match_spec.py#L619-L623

Unfortunately, I also don't know what to do with this.

**Comment by wolfv** [comment]
Looks like the idea was to have conditional dependencies? https://github.com/conda/conda/issues/7592

**Comment by baszalmstra** [comment]
Im going to leave the status quo for the moment.
