### ISSUE TITLE
Fix panic in matchspec parser

### ISSUE THREAD

**Issue by aochagavia** [mamba-org/rattler#640]
The matchspec parser contains a call to `unimplemented!` (see [here](https://github.com/mamba-org/rattler/blob/e1eea9acf47cb57ee339a49f2fd794de2d602d45/crates/rattler_conda_types/src/match_spec/parse.rs#L390)). For a program that accepts arbitrary matchspecs, that means specific matchspecs could cause the program to unexpectedly crash. I think it'd make sense to extend `ParseMatchSpecError ` with an additional variant for unimplemented bits, to avoid panics.

Would you welcome a PR for this?

**Comment by wolfv** [comment]
Sounds good to me! Even better would be to implement whatever conda does there :) but getting rid of panics is always good
