### ISSUE TITLE
Race condition in `link_file` leads to spurious errors (and linking fails)

### ISSUE THREAD

**Issue by aochagavia** [mamba-org/rattler#642]
### Steps to reproduce

This is somewhat complicated to reproduce, so I created a small program that runs code in a loop until it fails. [Here it is](https://github.com/aochagavia/rattler-issue-reproducer)! Note that my reproducer uses a [patched version of rattler](https://github.com/aochagavia/rattler/commit/b5db458893c4e2b1ee087115a31b259ab5b0f819), which includes a few printlns to explain what's going on.

I suggest you `cargo run` it and see for yourself (it should take less than 1 second, after building). The output should be self-explanatory :)

### Root cause of the race

(I might be wrong about this, but below is the only explanation that makes sense as far as my knowledge goes)

The race condition is related to hashing symlinked files. That process works in two steps:

1. Create the symlink.
2. Open the symlinked file, through the symlink we just created, and hash it.

The problem, as I understand it, is that the symlinked file points to another file in the prefix. However, there is no guarantee that the target file is already present in the prefix! Since linking is multi-threaded, there's a chance that the target file will be linked _after_ the symlink, leading to a crash because the hasher cannot find the file it wants to hash.

Here's a link to the relevant code: https://github.com/mamba-org/rattler/blob/e1eea9acf47cb57ee339a49f2fd794de2d602d45/crates/rattler/src/install/link.rs#L271-L272

### Solution

I'm not sure what conda mandates in the case of symlinks, but if we are lucky maybe we can skip hashing them altogether. Otherwise we'll need some mechanism to wait for the target files to be ready, instead of racing.

**Comment by baszalmstra** [comment]
A workaround/solution is #641

**Comment by baszalmstra** [comment]
We just merged #641 as a temporary solution. Would you be able to verify that this fixes the issue?
