### ISSUE TITLE
CTRL-C doesn't work with py-rattler

### ISSUE THREAD

**Issue by JeanChristopheMorinPerso** [mamba-org/rattler#665]
Hello, I made a script that uses py-rattler and it seems like I can't stop the script using CTRL-C. Or at least the `rattler.solve` function can't be cancelled with CTRL-C.

Is there any trick to make it work is is this a bug?

Thanks!

**Comment by wolfv** [comment]
Good find! We actually made the solver "cancellable" so in theory this should work fine. But the CTRL+C behavior with bindings is always a bit tricky. 

https://pyo3.rs/main/faq#ctrl-c-doesnt-do-anything-while-my-rust-code-is-executing

We should be able to use `Python::check_signals` to handle CTRL+C that is caught by the Python process. We need to find a mechanism to wire this up to our long-running functions (e.g. downloading, solving, ...).

**Comment by JeanChristopheMorinPerso** [comment]
Interestingly, the new async `solve` on main solves the problem. I only saw that after spending a couple of hours trying what you suggested...

**Comment by wolfv** [comment]
great!

**Comment by JeanChristopheMorinPerso** [comment]
Just tried with py-rattler 0.6.0 and it seems to be fixed now. I'm going to close this.

**Comment by wolfv** [comment]
Great!

**Comment by wolfv** [comment]
Btw. if you want to try a lightning fast experience, you can try the conda-forge channel from `https://fast.prefix.dev/conda-forge`. That uses the sharded repodata (but packages still come from the regular Anaconda server).
