### ISSUE TITLE
Timestamp in RepoDataRecord is in seconds instead of milliseconds

### ISSUE THREAD

**Issue by JeanChristopheMorinPerso** [mamba-org/rattler#700]
Hello, I noticed that the timestamp attached to a RepoDataRecord in py-rattler seems to be in seconds instead of being in milliseconds.

From what I understand, this seems to be caused by https://github.com/mamba-org/rattler/blob/a91ca46e49a75e8065d0578760626bfeab3782c4/py-rattler/src/record.rs#L212

According to https://docs.rs/chrono/latest/chrono/struct.DateTime.html#method.timestamp, the timestamp method returns seconds.

The thing is that in repodata.json, the timestamps are in milliseconds, not seconds so we loose precision.

Is this intentional?

**Comment by baszalmstra** [comment]
That's not intentional and something I would consider a bug. 

Funny note, timestamp in repodata are also not consistent, some are in milliseconds and some are in seconds.

Anyhow, yeah it would be better to return a datetime I think! Would you be able to create a PR? Could we also construct a datetime from milliseconds though?

**Comment by JeanChristopheMorinPerso** [comment]
```
$ for plat in {linux-{64,aarch64},win-64,osx-{64,arm64},noarch}; do curl -s https://conda.anaconda.org/conda-forge/$plat/repodata.json | jq '."packages.conda"[].timestamp, .packages[].timestamp' -r | awk '{print length()}' | sort -n | uniq -c; done
33149 4
441126 13
156084 13
27654 4
279888 13
32606 4
387859 13
131365 13
1660 4
192101 13
```
13 is milliseconds and 4 is "none", so no timestamps. Same on main:
```
$ for plat in {linux-{64,aarch64},win-64,osx-{64,arm64},noarch}; do curl -s https://repo.anaconda.com/pkgs/main/$plat/repodata.json | jq '."packages.conda"[].timestamp, .packages[].timestamp' -r | awk '{print length()}' | sort -n | uniq -c; done
  19 4
77091 13
33129 13
  15 4
69661 13
  15 4
74117 13
29483 13
   4 4
9380 13
```
So I don't see any timestamps in seconds on conda-forge and main.

**Comment by JeanChristopheMorinPerso** [comment]
>Could we also construct a datetime from milliseconds though?

From Python no. You have to do a small dance in Python to convert a timestamps with milliseconds precision to a datetime object, something like `int(latest.timestamp / 1000.0)`. But for rust > Python, I don't know. Based on https://pyo3.rs/v0.21.2/conversions/tables it seems to be doable?

**Comment by wolfv** [comment]
> So I don't see any timestamps in seconds on conda-forge and main.

Maybe the new conda-index is already doing the normalization :) But it was definitely a thing at some point.

**Comment by JeanChristopheMorinPerso** [comment]
Looking at py03, to return a datetime object to python, we would need to update to at least 0.21 and and stop using the abi3... I'm guessing that dropping abi3 would be a no go right?

**Comment by wolfv** [comment]
@JeanChristopheMorinPerso we are actually using a "double-wrap" so you can do arbitrary stuff on the Python side before it's being handed to the user. It should be quite straightforward to get a integer from Rust and wrap it in the Python datetime object.

**Comment by wolfv** [comment]
@JeanChristopheMorinPerso let me know what you think about the implementation in #706 - it returns a `datetime.datetime` instead of an integer.

**Comment by JeanChristopheMorinPerso** [comment]
Thanks!
