### ISSUE TITLE
`InvalidBracket` for matchspec

### ISSUE THREAD

**Issue by baszalmstra** [mamba-org/rattler#717]
Parsing of invalid matchspec `ray[default,data] >=2.9.0,<3.0.0` fails with 

```
called `Result::unwrap()` on an `Err` value: InvalidBracket
```

Even though the matchspec is invalid, we should not fail with a panic!

See https://github.com/prefix-dev/pixi/issues/1469

**Comment by wolfv** [comment]
Maybe we can ignore invalid matchspecs

**Comment by baszalmstra** [comment]
Yeah for sure! Currently we unwrap in the parsing code though..
