### ISSUE TITLE
Create repodata records from package urls

### ISSUE THREAD

**Issue by ruben-arts** [mamba-org/rattler#720]
This feature would be in preparation to solving with only a `Url` as `MatchSpec`.
We need to create repodata to send to the solver but the information for the package record needs to be fetched from the package itself instead of a repodata file. 

This needs to be an async funtion to fetch the data from the package by downloading it to the package cache first.

**Comment by baszalmstra** [comment]
Closed by https://github.com/mamba-org/rattler/pull/725
