### ISSUE TITLE
Matchspec::from_string gives RegexConstraintsNotSupported for X.Y.Z.*.

### ISSUE THREAD

**Issue by AaronOpfer** [mamba-org/rattler#722]
Apparently, package `dlib-19.0-np110py27_blas_openblas_200.tar.bz2` from conda-forge has a dependency `openblas 0.2.18|0.2.18.*.` (note the trailing dot) , but `rattler_conda_types::MatchSpec` rejects this: `InvalidVersionSpec(InvalidConstraint(RegexConstraintsNotSupported))`. Previously this wasn't an error in rattler_conda_types 0.24.0 , but now is in rattler_conda_types 0.25.1.

[Discord conversation](https://discord.com/channels/1082332781146800168/1082338253925003385/1247347616879214654)

The following release of `dlib`, `19.7`, seems to have been corrected: it depends on `openblas 0.2.20|0.2.20.*`.

**Comment by wolfv** [comment]
I think you can use the "lenient" parsing mode to ignore these, right?

**Comment by baszalmstra** [comment]
Yes, but this specific case still fails to parse. My idea was to add this exception to the lenient parser.
