### ISSUE TITLE
Use prefetched repodatas in `solve()`?

### ISSUE THREAD

**Issue by jaimergp** [mamba-org/rattler#730]
In py_rattler 0.5, the `solve` function expected a parameter `available_packages` with a list of `SparseRepodata`, which had been previously fetched with `fetch()` or equivalent. In 0.6, now we pass `channels` + `Gateway`. This is excellent as a high-level API!

... but now I can't pass my previously prefetched repodatas 😬 I would need a way to pass a list of `(Sparse)Repodata` objects to the solver again, maybe as an overloaded signature, or a different function altogether. Would it be possible to offer the `available_packages` logic in some way? The reason for this is integrating with conda, where the repodata must be fetched with their networking stack for different reasons.

Thanks!

**Comment by baszalmstra** [comment]
Just released py_rattler 0.6.3 which contains the new function!

**Comment by jaimergp** [comment]
That was quick, thanks!!

**Comment by jaimergp** [comment]
I see it on PyPI and it's working great. Wondering if the lack of a GH Release (only the tag is published) will cause interference with the eventual conda-forge release.

**Comment by jaimergp** [comment]
nvm semiauto mode works great https://github.com/conda-forge/py-rattler-feedstock/pull/18
