### ISSUE TITLE
Implement solver error messages from mamba

### ISSUE THREAD

**Issue by wolfv** [mamba-org/rattler#80]
We should implement the solver error message algorithm that's found in mamba (for the libsolv solver): 

- Implementation: https://github.com/mamba-org/mamba/blob/main/libmamba/src/core/solver.cpp
- Blog post: https://medium.com/@AntoineProuvost/managing-conflicts-with-mamba-6a5fa10ed6a

**Comment by baszalmstra** [comment]
@wolfv has started some work on this in #95

**Comment by wolfv** [comment]
We have the nice solver error messages in the new libsolv implementation (libsolv-rs).
