### ISSUE TITLE
Implement the `jlap` format

### ISSUE THREAD

**Issue by wolfv** [mamba-org/rattler#81]
It would be nice to implement the `jlap` format for partial repodata updates (using a specific sequenece of JSON patch applications).

That makes interactive usage faster because only a subset of the entire data needs to be fetched over the network.

**Comment by dholth** [comment]
This is the predecessor to the jlap forma in rust https://github.com/dholth/jdiff/. It is basically the same except that there is an array of patches instead of a line-based format.

It turns out Python has very fast json support (generating the patches on pypi was faster), and this was put aside.

**Comment by wolfv** [comment]
Just for reference, this was the prototype I made in C++: https://github.com/mamba-org/mamba/pull/2029/files
