### ISSUE TITLE
FYI rust matchspec

### ISSUE THREAD

**Issue by dholth** [mamba-org/rattler#88]
https://github.com/remkade/matchspec

**Comment by baszalmstra** [comment]
Thanks @dholth! I wasn't aware of this library. Is there anything from this library that you think we would benefit from? Rattler also contains its own [matchspec implementation](https://mamba-org.github.io/rattler/rattler_conda_types/struct.MatchSpec.html).

**Comment by dholth** [comment]
No, I haven't personally worked on that library.

**Comment by wolfv** [comment]
Thanks @dholth I am going to close this issue. Would be fun to talk with @remkade or anyone involved though!

**Comment by remkade** [comment]
Happy to talk about it any time! Its kind of an exploratory way of speeding up the Python `MatchSpec` aimed mainly at non-conda use cases. We use it internally for parsing and matching in data processing jobs.
