### ISSUE TITLE
Implement build string version comparison

### ISSUE THREAD

**Issue by baszalmstra** [mamba-org/rattler#96]
Our matchspec implementation currently doesn't implement build string version comparison like `>6` in `python 3.9.3[build_number=">6"]`. 

This would be a nice addition! 

Conda implementation: https://github.com/conda/conda/blob/main/conda/models/version.py#L613

**Comment by YeungOnion** [comment]
Is this still needed? I'd like to take a look.

Additionally, the link is to main branch instead of commit hash, so to make sure, are you referring to the method below?

```py
BuildNumberMatch.get_matcher
```

Anything else to know?

**Comment by baszalmstra** [comment]
Yes this is still needed! :)

Indeed, the link should point to [the `BuildNumberMatch` class](https://github.com/conda/conda/blob/d527576f8033731cac9196494b9a1061b29091ba/conda/models/version.py#L628).

**Comment by YeungOnion** [comment]
Thoughts on new [dependency](https://crates.io/crates/version-compare) for more general version matching? Seems well established and has no depends. Might mess around with it for fun.

**Comment by baszalmstra** [comment]
Conda version parsing and ordering is very specific. I doubt the approach used by that crate will provide the correct result.

**Comment by baszalmstra** [comment]
Implemented in #346
